import { test, expect } from "@playwright/test";

test.describe("Marketing pages", () => {
  /* ------------------------------------------------------------------ */
  /*  Homepage                                                           */
  /* ------------------------------------------------------------------ */

  test("homepage loads and has hero section with CTA", async ({ page }) => {
    await page.goto("/");

    // Hero heading
    await expect(
      page.getByRole("heading", { name: /run your business with clarity/i }),
    ).toBeVisible();

    // Subtext generated by TextGenerateEffect
    await expect(page.getByText(/enterprise-grade ERP/i)).toBeVisible();

    // Primary CTA — "Get Started"
    const getStartedLink = page.getByRole("link", { name: /get started/i }).first();
    await expect(getStartedLink).toBeVisible();

    // Secondary CTA — "See Features"
    await expect(
      page.getByRole("link", { name: /see features/i }),
    ).toBeVisible();
  });

  test("homepage has navigation bar with links", async ({ page }) => {
    await page.goto("/");

    const nav = page.locator("nav");
    await expect(nav).toBeVisible();

    // Nav links
    await expect(nav.getByRole("link", { name: /features/i })).toBeVisible();
    await expect(nav.getByRole("link", { name: /pricing/i })).toBeVisible();
    await expect(nav.getByRole("link", { name: /about/i })).toBeVisible();

    // Auth links
    await expect(nav.getByText(/sign in/i)).toBeVisible();
    await expect(nav.getByRole("link", { name: /get started/i })).toBeVisible();
  });

  test("homepage shows feature bento grid", async ({ page }) => {
    await page.goto("/");

    await expect(
      page.getByRole("heading", { name: /everything you need/i }),
    ).toBeVisible();

    // Check a few module cards from the bento grid
    await expect(page.getByText("Sales & Invoicing")).toBeVisible();
    await expect(page.getByText("Procurement")).toBeVisible();
    await expect(page.getByText("Inventory Management")).toBeVisible();
  });

  test("homepage shows pricing section with all 3 plans", async ({ page }) => {
    await page.goto("/");

    // Pricing section heading
    await expect(
      page.getByRole("heading", { name: /simple, transparent pricing/i }).first(),
    ).toBeVisible();

    // Plan names
    await expect(page.getByText("Starter").first()).toBeVisible();
    await expect(page.getByText("Business").first()).toBeVisible();
    await expect(page.getByText("Enterprise").first()).toBeVisible();
  });

  /* ------------------------------------------------------------------ */
  /*  Pricing page                                                       */
  /* ------------------------------------------------------------------ */

  test("pricing page shows all 3 plans with correct monthly prices", async ({ page }) => {
    await page.goto("/pricing");

    // Page heading
    await expect(
      page.getByRole("heading", { name: /simple, transparent pricing/i }),
    ).toBeVisible();

    // Plan names should be visible
    await expect(page.getByText("Starter").first()).toBeVisible();
    await expect(page.getByText("Business").first()).toBeVisible();
    await expect(page.getByText("Enterprise").first()).toBeVisible();

    // Monthly prices: $500, $1,000, $5,000
    await expect(page.getByText("$500").first()).toBeVisible();
    await expect(page.getByText("$1,000").first()).toBeVisible();
    await expect(page.getByText("$5,000").first()).toBeVisible();
  });

  test("pricing page has billing toggle (monthly/annual)", async ({ page }) => {
    await page.goto("/pricing");

    await expect(page.getByText("Monthly")).toBeVisible();
    await expect(page.getByText("Annual")).toBeVisible();

    // The toggle switch
    const toggle = page.getByRole("switch");
    await expect(toggle).toBeVisible();
  });

  test("pricing page shows module comparison table", async ({ page }) => {
    await page.goto("/pricing");

    // Column headers in the module table
    const table = page.locator("table").first();
    await expect(table).toBeVisible();
    await expect(table.getByText("Module")).toBeVisible();
    await expect(table.getByText("Starter").first()).toBeVisible();
    await expect(table.getByText("Business").first()).toBeVisible();
    await expect(table.getByText("Enterprise").first()).toBeVisible();
  });

  test("pricing page has CTA buttons for each plan", async ({ page }) => {
    await page.goto("/pricing");

    // Starter and Business have "Start free trial", Enterprise has "Talk to sales"
    const trialLinks = page.getByRole("link", { name: /start free trial/i });
    await expect(trialLinks.first()).toBeVisible();

    await expect(
      page.getByRole("link", { name: /talk to sales/i }),
    ).toBeVisible();
  });

  /* ------------------------------------------------------------------ */
  /*  Modules page                                                       */
  /* ------------------------------------------------------------------ */

  test("modules page loads and shows module catalog", async ({ page }) => {
    await page.goto("/modules");

    await expect(
      page.getByRole("heading", { name: /module catalog/i }),
    ).toBeVisible();

    // Shows module count text
    await expect(page.getByText(/\d+ modules/i).first()).toBeVisible();

    // Category tabs are visible (at least "All" tab)
    await expect(page.getByRole("button", { name: /all/i }).first()).toBeVisible();

    // Some module cards should be rendered
    await expect(page.getByText("General Ledger")).toBeVisible();
  });

  /* ------------------------------------------------------------------ */
  /*  About page                                                         */
  /* ------------------------------------------------------------------ */

  test("about page loads with company information", async ({ page }) => {
    await page.goto("/about");

    // The about page should contain key beliefs / mission content
    await expect(page.getByText(/ERP should work on day one/i)).toBeVisible();
    await expect(page.getByText(/Your data stays yours/i)).toBeVisible();
  });

  /* ------------------------------------------------------------------ */
  /*  Navigation between pages                                           */
  /* ------------------------------------------------------------------ */

  test("can navigate from homepage to pricing page", async ({ page }) => {
    await page.goto("/");

    // Click the Pricing link in the navbar
    const nav = page.locator("nav");
    await nav.getByRole("link", { name: /pricing/i }).click();

    await expect(page).toHaveURL(/\/pricing/);
    await expect(
      page.getByRole("heading", { name: /simple, transparent pricing/i }),
    ).toBeVisible();
  });

  test("can navigate from homepage to modules page", async ({ page }) => {
    await page.goto("/");

    // Click the Features link in the navbar (which points to /modules)
    const nav = page.locator("nav");
    await nav.getByRole("link", { name: /features/i }).click();

    await expect(page).toHaveURL(/\/modules/);
    await expect(
      page.getByRole("heading", { name: /module catalog/i }),
    ).toBeVisible();
  });

  test("can navigate from homepage to about page", async ({ page }) => {
    await page.goto("/");

    const nav = page.locator("nav");
    await nav.getByRole("link", { name: /about/i }).click();

    await expect(page).toHaveURL(/\/about/);
    await expect(page.getByText(/ERP should work on day one/i)).toBeVisible();
  });
});
